/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Admin
 */
public class ZwrotKsiazki extends javax.swing.JFrame {
    
    Connection polaczenie;
    ResultSet result;
    PreparedStatement oswiadczenie;

    /**
     * Creates new form ZwrotKsiazki
     */
    public ZwrotKsiazki() {
        super("Zwrot Ksiazki");
        initComponents();
        polaczenie = BazaDanych.Baza();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Album = new javax.swing.JTextField();
        Imie = new javax.swing.JTextField();
        Nazwisko = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Wydzial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnKsiazka = new javax.swing.JButton();
        btnStudent = new javax.swing.JButton();
        Nazwa = new javax.swing.JTextField();
        Autor = new javax.swing.JTextField();
        Rok = new javax.swing.JTextField();
        Strony = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dataZwrotu = new datechooser.beans.DateChooserCombo();
        btnOk = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnAnuluj = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        listaKsiazek = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        dataWydania = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jWyjscie = new javax.swing.JMenuItem();
        jWyloguj = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jDane = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nazwisko");

        jLabel10.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("E-mail");

        Album.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Album.setMinimumSize(new java.awt.Dimension(200, 30));
        Album.setPreferredSize(new java.awt.Dimension(200, 30));
        Album.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlbumActionPerformed(evt);
            }
        });

        Imie.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Imie.setMinimumSize(new java.awt.Dimension(200, 30));
        Imie.setPreferredSize(new java.awt.Dimension(200, 30));
        Imie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImieActionPerformed(evt);
            }
        });

        Nazwisko.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Nazwisko.setMinimumSize(new java.awt.Dimension(200, 30));
        Nazwisko.setPreferredSize(new java.awt.Dimension(200, 30));

        Email.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Email.setMinimumSize(new java.awt.Dimension(200, 30));
        Email.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel11.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Nr albumu");

        Wydzial.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Wydzial.setMinimumSize(new java.awt.Dimension(200, 30));
        Wydzial.setPreferredSize(new java.awt.Dimension(200, 30));
        Wydzial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WydzialActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Książka");

        jLabel12.setFont(new java.awt.Font("Arial Narrow", 0, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Student");

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rok wydania");

        jLabel13.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Data zwrotu");

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ilość stron");

        btnKsiazka.setBackground(new java.awt.Color(39, 14, 2));
        btnKsiazka.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnKsiazka.setForeground(new java.awt.Color(255, 255, 255));
        btnKsiazka.setText("Wybież");
        btnKsiazka.setBorder(null);
        btnKsiazka.setPreferredSize(new java.awt.Dimension(200, 30));
        btnKsiazka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKsiazkaActionPerformed(evt);
            }
        });

        btnStudent.setBackground(new java.awt.Color(39, 14, 2));
        btnStudent.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnStudent.setText("Szukaj");
        btnStudent.setBorder(null);
        btnStudent.setPreferredSize(new java.awt.Dimension(200, 30));
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });

        Nazwa.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Nazwa.setMinimumSize(new java.awt.Dimension(200, 30));
        Nazwa.setPreferredSize(new java.awt.Dimension(200, 30));
        Nazwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NazwaActionPerformed(evt);
            }
        });

        Autor.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Autor.setMinimumSize(new java.awt.Dimension(200, 30));
        Autor.setPreferredSize(new java.awt.Dimension(200, 30));

        Rok.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Rok.setMinimumSize(new java.awt.Dimension(200, 30));
        Rok.setPreferredSize(new java.awt.Dimension(200, 30));

        Strony.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        Strony.setMinimumSize(new java.awt.Dimension(200, 30));
        Strony.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID książki");

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nazwa");

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Autor");

        dataZwrotu.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    dataZwrotu.setLocale(new java.util.Locale("pl", "PL", ""));
    dataZwrotu.setFieldFont(new java.awt.Font("Arial Narrow", java.awt.Font.PLAIN, 17));
    dataZwrotu.setNavigateFont(new java.awt.Font("Arial Narrow", java.awt.Font.PLAIN, 11));
    dataZwrotu.addSelectionChangedListener(new datechooser.events.SelectionChangedListener() {
        public void onSelectionChange(datechooser.events.SelectionChangedEvent evt) {
            dataZwrotuOnSelectionChange(evt);
        }
    });
    dataZwrotu.addCommitListener(new datechooser.events.CommitListener() {
        public void onCommit(datechooser.events.CommitEvent evt) {
            dataZwrotuOnCommit(evt);
        }
    });

    btnOk.setBackground(new java.awt.Color(39, 14, 2));
    btnOk.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
    btnOk.setForeground(new java.awt.Color(255, 255, 255));
    btnOk.setText("Potwierdzić");
    btnOk.setBorder(null);
    btnOk.setPreferredSize(new java.awt.Dimension(200, 30));
    btnOk.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnOkActionPerformed(evt);
        }
    });

    jLabel7.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
    jLabel7.setForeground(new java.awt.Color(255, 255, 255));
    jLabel7.setText("Imię");

    btnAnuluj.setBackground(new java.awt.Color(39, 14, 2));
    btnAnuluj.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
    btnAnuluj.setForeground(new java.awt.Color(255, 255, 255));
    btnAnuluj.setText("Anuluj");
    btnAnuluj.setBorder(null);
    btnAnuluj.setPreferredSize(new java.awt.Dimension(200, 30));
    btnAnuluj.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAnulujActionPerformed(evt);
        }
    });

    jLabel8.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(255, 255, 255));
    jLabel8.setText("Wydział");

    listaKsiazek.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
    listaKsiazek.setPreferredSize(new java.awt.Dimension(200, 30));
    listaKsiazek.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            listaKsiazekItemStateChanged(evt);
        }
    });
    listaKsiazek.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            listaKsiazekActionPerformed(evt);
        }
    });

    jLabel14.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
    jLabel14.setForeground(new java.awt.Color(255, 255, 255));
    jLabel14.setText("Data wydania");

    dataWydania.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
    dataWydania.setMinimumSize(new java.awt.Dimension(200, 30));
    dataWydania.setPreferredSize(new java.awt.Dimension(200, 30));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Wydzial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Album, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Imie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Nazwisko, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(jLabel2)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(btnKsiazka, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(Autor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Nazwa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(listaKsiazek, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Rok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Strony, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnAnuluj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(330, 330, 330)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dataWydania, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dataZwrotu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(3, 3, 3)))
            .addGap(38, 38, 38))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jLabel12))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jLabel11)
                .addComponent(Album, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(listaKsiazek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnKsiazka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Nazwa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(Imie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(Nazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(Rok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(Wydzial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(Strony, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(44, 44, 44)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dataWydania, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(dataZwrotu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGap(38, 38, 38)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnAnuluj, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(68, Short.MAX_VALUE))
    );

    jMenu1.setText("File");

    jMenu3.setText("Dodać...");

    jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem2.setText("nową książkę");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem2ActionPerformed(evt);
        }
    });
    jMenu3.add(jMenuItem2);

    jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem3.setText("nowego studenta");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem3ActionPerformed(evt);
        }
    });
    jMenu3.add(jMenuItem3);

    jMenu1.add(jMenu3);

    jWyjscie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
    jWyjscie.setText("Wyjście");
    jWyjscie.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jWyjscieActionPerformed(evt);
        }
    });
    jMenu1.add(jWyjscie);

    jWyloguj.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
    jWyloguj.setText("Wyloguj się    ");
    jWyloguj.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jWylogujActionPerformed(evt);
        }
    });
    jMenu1.add(jWyloguj);

    jMenuBar1.add(jMenu1);

    jMenu2.setText("Edit");

    jDane.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
    jDane.setText("Dane   ");
    jDane.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jDaneActionPerformed(evt);
        }
    });
    jMenu2.add(jDane);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlbumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlbumActionPerformed

    private void ImieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImieActionPerformed

    private void WydzialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WydzialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WydzialActionPerformed

    private void btnKsiazkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKsiazkaActionPerformed
        // TODO add your handling code here:
        String sql="select nazwa,autor,rokWydania,iloscStron,dataWydania from WydaneKsiazki where IDksiazki=?";
        try{
           oswiadczenie = polaczenie.prepareStatement(sql);
           oswiadczenie.setString(1, listaKsiazek.getSelectedItem().toString());
            result = oswiadczenie.executeQuery();
            if(result.next()){
            String add1= result.getString("nazwa");
            Nazwa.setText(add1);
            String add2= result.getString("autor");
            Autor.setText(add2);
            String add3= result.getString("rokWydania");
            Rok.setText(add3);
            String add4= result.getString("iloscStron");         
            Strony.setText(add4);
            String add5= result.getString("dataWydania");         
            dataWydania.setText(add5);
            result.close();
            oswiadczenie.close();
           }
           else{
               JOptionPane.showMessageDialog(null, "Książka nie została znaleziona");
           }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        } finally{
            try{
               result.close();
               oswiadczenie.close();
            }catch(Exception ex){            
            }
        }      
     
    }//GEN-LAST:event_btnKsiazkaActionPerformed

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
        // TODO add your handling code here:
        String sql="select imie,nazwisko,wydzial,email,IDksiazki from WydaneKsiazki where IDstudenta=?";
        try{
           oswiadczenie = polaczenie.prepareStatement(sql);
           oswiadczenie.setString(1, Album.getText());
           result = oswiadczenie.executeQuery();
           if(result.next()){
            listaKsiazek.removeAllItems();
            String add1 = result.getString("imie");
            Imie.setText(add1);
            String add2 = result.getString("nazwisko");
            Nazwisko.setText(add2);
            String add3 = result.getString("wydzial");
            Wydzial.setText(add3);
            String add4 = result.getString("email");
            Email.setText(add4);
            utwozListe();            
            result.close();
            oswiadczenie.close();
           }
           else{
               JOptionPane.showMessageDialog(null, "Student nie został znaleziony lub nie maję wypozyczonych książek.");
           }
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        } finally{
            try{
               result.close();
               oswiadczenie.close();
            }catch(Exception ex){            
            }
        }        
    }//GEN-LAST:event_btnStudentActionPerformed

    private void NazwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NazwaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NazwaActionPerformed

    private void dataZwrotuOnSelectionChange(datechooser.events.SelectionChangedEvent evt) {//GEN-FIRST:event_dataZwrotuOnSelectionChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dataZwrotuOnSelectionChange

    private void dataZwrotuOnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dataZwrotuOnCommit
        // TODO add your handling code here:
    }//GEN-LAST:event_dataZwrotuOnCommit

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        String sql="insert into ZwrotKsiazki(IDstudenta,imie,nazwisko,wydzial,email,IDksiazki,nazwa,autor,rokWydania,iloscStron,dataWydania,dataZwrotu) values (?,?,?,?,?,?,?,?,?,?,?,?)";
        try{
            oswiadczenie = polaczenie.prepareStatement(sql);
            oswiadczenie.setString(1,Album.getText());
            oswiadczenie.setString(2,Imie.getText());
            oswiadczenie.setString(3,Nazwisko.getText());
            oswiadczenie.setString(4,Wydzial.getText());
            oswiadczenie.setString(5,Email.getText());
            oswiadczenie.setString(6,listaKsiazek.getSelectedItem().toString());
            oswiadczenie.setString(7,Nazwa.getText());
            oswiadczenie.setString(8,Autor.getText());
            oswiadczenie.setString(9,Rok.getText());
            oswiadczenie.setString(10,Strony.getText());
            oswiadczenie.setString(11,dataWydania.getText());
            oswiadczenie.setString(12, (String) dataZwrotu.getText());
            oswiadczenie.execute();
            JOptionPane.showMessageDialog(null, "Zwrot został dokonany.");
            result.close();
            oswiadczenie.close();
            Usunac();
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }       

    }//GEN-LAST:event_btnOkActionPerformed

    private void btnAnulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnulujActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Menu ob = new Menu();
        ob.setVisible(true);
    }//GEN-LAST:event_btnAnulujActionPerformed

    private void listaKsiazekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaKsiazekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaKsiazekActionPerformed

    private void listaKsiazekItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaKsiazekItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listaKsiazekItemStateChanged

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        NowaKsiazka ob = new NowaKsiazka();
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        NowyStudent ob = new NowyStudent();
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jWyjscieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWyjscieActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jWyjscieActionPerformed

    private void jWylogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWylogujActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Login ob=new Login();
        ob.setVisible(true);
    }//GEN-LAST:event_jWylogujActionPerformed

    private void jDaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDaneActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Info ob = new Info();
        ob.setVisible(true);
    }//GEN-LAST:event_jDaneActionPerformed

    
    private void utwozListe(){

        try{
        String sql="select IDksiazki from WydaneKsiazki where IDstudenta=?";            
            oswiadczenie = polaczenie.prepareStatement(sql);
            oswiadczenie.setString(1, Album.getText());
            result = oswiadczenie.executeQuery();
            
            while(result.next()){
                String item = result.getString("IDksiazki");
                listaKsiazek.addItem(item);
            }
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        } finally{
            try{
               result.close();
               oswiadczenie.close();
            } catch(Exception ex){            
            }   
        }            
    }
    
    public void Usunac(){
        String sql="delete from WydaneKsiazki where IDksiazki=?";
        try{
           oswiadczenie = polaczenie.prepareStatement(sql);
           oswiadczenie.setString(1, listaKsiazek.getSelectedItem().toString());
           oswiadczenie.executeUpdate();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZwrotKsiazki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZwrotKsiazki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZwrotKsiazki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZwrotKsiazki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZwrotKsiazki().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Album;
    private javax.swing.JTextField Autor;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Imie;
    private javax.swing.JTextField Nazwa;
    private javax.swing.JTextField Nazwisko;
    private javax.swing.JTextField Rok;
    private javax.swing.JTextField Strony;
    private javax.swing.JTextField Wydzial;
    private javax.swing.JButton btnAnuluj;
    private javax.swing.JButton btnKsiazka;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnStudent;
    private javax.swing.JTextField dataWydania;
    private datechooser.beans.DateChooserCombo dataZwrotu;
    private javax.swing.JMenuItem jDane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jWyjscie;
    private javax.swing.JMenuItem jWyloguj;
    private javax.swing.JComboBox<String> listaKsiazek;
    // End of variables declaration//GEN-END:variables
}
